stages:
  data_cleaning:
    cmd: python src/data/data-cleaning.py
    
    deps:
    - data/raw/train.csv
    - src/data/data-cleaning.py

    outs:
    - data/cleaned/cleaned_data.csv

  data_prepraration:
    cmd: python src/data/data-preparation.py

    params: 
    - Data_Preparation.test_size
    - Data_Preparation.random_state

    deps:
    - data/cleaned/cleaned_data.csv
    - src/data/data-preparation.py

    outs:
    - data/interim/train_subset.csv
    - data/interim/test_subset.csv