stages:
  data_cleaning:
    cmd: python src/data/data-cleaning.py
    
    deps:
    - data/raw/train.csv
    - src/data/data-cleaning.py

    outs:
    - data/cleaned/cleaned_data.csv

  data_prepraration:
    cmd: python src/data/data-preparation.py

    params: 
    - Data_Preparation.test_size
    - Data_Preparation.random_state

    deps:
    - data/cleaned/cleaned_data.csv
    - src/data/data-preparation.py

    outs:
    - data/interim/train_subset.csv
    - data/interim/test_subset.csv

  data_preprocessing:
    cmd: python src/features/data-preprocessing.py

    deps: 
    - data/interim/train_subset.csv
    - data/interim/test_subset.csv
    - src/features/data-preprocessing.py

    outs:
    - models/preprocessor.joblib
    - data/processed/train_trans.csv
    - data/processed/test_trans.csv

  train:
    cmd: python src/models/train.py 

    params: 
    - Train.Random_Forest
    - Train.LightGBM

    deps:
    - data/processed/train_trans.csv
    - src/models/train.py 

    outs:
    - models/model.joblib
    - models/stacking_regressor.joblib
    - models/power_transformer.joblib

